# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempo < Formula
  desc "Terminal UI for Temporal workflow management"
  homepage "https://github.com/atterpac/tempo"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atterpac/tempo/releases/download/v0.0.11/tempo_darwin_amd64.tar.gz"
      sha256 "1bc1eaf215f24ff334ba8def41a2d5a5dd9875379fff60d58d412b9bf19b6f21"

      def install
        bin.install "tempo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atterpac/tempo/releases/download/v0.0.11/tempo_darwin_arm64.tar.gz"
      sha256 "54b8614d99e7704fec4646865ac62d30aa5a330b13b73b0093f7bc8f8bf4fb6d"

      def install
        bin.install "tempo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atterpac/tempo/releases/download/v0.0.11/tempo_linux_amd64.tar.gz"
      sha256 "dfcf5ed4a1c617ad477e0062966e183fcf8171f077efa8ab2408310e8f39b618"
      def install
        bin.install "tempo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atterpac/tempo/releases/download/v0.0.11/tempo_linux_arm64.tar.gz"
      sha256 "72b87ff403430f8acc06358e4dbb904150a7ba3d8a8747a3dce129bed5de0d15"
      def install
        bin.install "tempo"
      end
    end
  end

  test do
    system "#{bin}/tempo", "--version"
  end
end
