# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempo < Formula
  desc "Terminal UI for Temporal workflow management"
  homepage "https://github.com/atterpac/tempo"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atterpac/tempo/releases/download/v0.0.12/tempo_darwin_amd64.tar.gz"
      sha256 "535d75c014a60545833f9a2adfe2155ede9519b75c53844fb3849004c2fe7629"

      def install
        bin.install "tempo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atterpac/tempo/releases/download/v0.0.12/tempo_darwin_arm64.tar.gz"
      sha256 "7f22b4a2c07ece9ac2636c5ddb669eab021741ed2d986a2914e83a4ca80ec277"

      def install
        bin.install "tempo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atterpac/tempo/releases/download/v0.0.12/tempo_linux_amd64.tar.gz"
      sha256 "10ef6a97c88685108f74f8a257bba0a9a8d63fe03efdd2758211aaef67a50249"
      def install
        bin.install "tempo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atterpac/tempo/releases/download/v0.0.12/tempo_linux_arm64.tar.gz"
      sha256 "2b72371be3c9c81bbaf5ec9e7e78ac54857d71b4a1f46450ab3b29b589a3dc51"
      def install
        bin.install "tempo"
      end
    end
  end

  test do
    system "#{bin}/tempo", "--version"
  end
end
